version: "2.4"
services:
  backend:
    tty: true
    init: true
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/root/app
      - backend_venv:/root/app/.venv
      - backend_pycache:/root/app/__pycache__

volumes:
  backend_venv:
  backend_pycache: