version: "2.4"
services:
  backend:
    tty: true
    init: true
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/scripts:/root/backend/scripts
      - ./backend/src:/root/backend/src
      - ./backend/.dockerignore:/root/backend/.dockerignore
      - ./backend/.gitignore:/root/backend/.gitignore
      - ./backend/Dockerfile:/root/backend/Dockerfile
      - ./backend/poetry.lock:/root/backend/poetry.lock
      - ./backend/pyproject.toml:/root/backend/pyproject.toml

      - backend_venv:/root/drilldev/.venv
      - backend_pycache:/root/drilldev/__pycache__

volumes:
  backend_venv:
  backend_pycache:
